find_package(Qt6 REQUIRED COMPONENTS Test)
set(APP_TEST_SOURCES ${PROJECT_SOURCES})
list(REMOVE_ITEM APP_TEST_SOURCES src/main.cpp)
list(TRANSFORM APP_TEST_SOURCES PREPEND "${PROJECT_SOURCE_DIR}/")
foreach(target IN ITEMS actionmanagertests srtests navigationtests)
    add_executable(${target} tst_${target}.cpp ${APP_TEST_SOURCES} "${PROJECT_SOURCE_DIR}/resources/resources.qrc")
    target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/src")
    set_target_properties(${target} PROPERTIES AUTOUIC_SEARCH_PATHS "${PROJECT_SOURCE_DIR}/src")
    target_link_libraries(${target} PRIVATE Qt6::Core Qt6::Gui Qt6::Network Qt6::Widgets Qt6::Svg
        qviewsr_i18n Qt6::Concurrent Qt6::Test PkgConfig::LCMS2 ZLIB::ZLIB GIF::GIF ${PLATFORM_SPECIFIC_LIBS})
    target_compile_definitions(${target} PRIVATE "VERSION=${PROJECT_VERSION}" QT_DEPRECATED_WARNINGS QT_NO_FOREACH
        "SR_SOURCE_DIR=\"${PROJECT_SOURCE_DIR}\"")
    if(QV_DISABLE_ONLINE_VERSION_CHECK)
        target_compile_definitions(${target} PRIVATE QV_DISABLE_ONLINE_VERSION_CHECK)
    endif()
    if(UNIX AND NOT APPLE AND NOT NO_X11)
        target_compile_definitions(${target} PRIVATE X11_LOADED)
    endif()
    if(WIN32 AND NOT NO_WIN32)
        target_compile_definitions(${target} PRIVATE WIN32_LOADED)
    endif()
    if(APPLE AND NOT NO_COCOA)
        target_compile_definitions(${target} PRIVATE COCOA_LOADED)
    endif()
endforeach()
add_test(NAME ActionManagerTests COMMAND actionmanagertests)
add_test(NAME SrTests COMMAND srtests)
add_test(NAME NavigationTests COMMAND navigationtests)
set_tests_properties(ActionManagerTests SrTests NavigationTests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen" TIMEOUT 180)
